function [axis_params] = axis_parameters_table_e()
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Function: axis_parameters_table_e()
% Goal    : Output a structure that contains all the axis parameters that
%           can be written to the EEPROM of the TMCM-1160.
%
% Structure fields:
% +-------------------------------------------------------+
% |Parameter name,{Parameter number, Min value, Max value}|
% +-------------------------------------------------------+
%
% IN      : -
% IN/OUT  : -
% OUT     : - axis_params: list of all EEPROM axis parameters for the
%                          TMCM-1160 with their MIN and MAX values
%
% Copyright 2018 The MathWorks, Inc.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

  % Constants of 2 power the number of bit
  MAX_0b  = 2^0 -1; MAX_1b  = 2^1 -1; MAX_8b  = 2^8 -1; 
  MAX_11b = 2^11-1; MAX_16b = 2^16-1;
  
  % Mnemonic encoding in decimal for the available axis parameters
  axis_params = struct(...
                'MAX_POSITIONING_SPEED'       ,{  4,  MAX_0b,MAX_11b},...
                'MAX_ACCELERATION'            ,{  5,  MAX_0b,MAX_11b},...
                'ABSOLUTE_MAX_CURRENT'        ,{  6,  MAX_0b, MAX_8b},...
                'STANDBY_CURRENT'             ,{  7,  MAX_0b, MAX_8b},...
                'RIGHT_LIM_SWITCH_DISABLE'    ,{ 12,  MAX_0b, MAX_1b},...
                'LEFT_LIM_SWITCH_DISABLE'     ,{ 13,  MAX_0b, MAX_1b},...
                'MIN_SPEED'                   ,{130,  MAX_0b,MAX_11b},...
                'RAMP_MODE'                   ,{138,  MAX_0b,      2},...
                'MICROSTEP_RESOLUTION'        ,{140,  MAX_0b,      8},...
                'SOFT_STOP_FLAG'              ,{149,  MAX_0b, MAX_1b},...
                'RAMP_DIVISOR'                ,{153,  MAX_0b,     13},...
                'PULSE_DIVISOR'               ,{154,  MAX_0b,     13},...
                'REFERENCE_SEARCH_MODE'       ,{193,  MAX_1b,      8},...
                'REFERENCING_SEARCH_SPEED'    ,{194,  MAX_0b,MAX_11b},...
                'REFERENCING_SWITCH_SPEED'    ,{195,  MAX_0b,MAX_11b},...
                'BOOST_CURRENT'               ,{200,  MAX_0b, MAX_8b},...
                'FREEWHEELING'                ,{204,  MAX_0b,MAX_16b},...
                'ENCODER_PRESCALER_SENSOSTEP' ,{210,     200,  25600},...
                'MAX_ENCODER_DEVIAT_SENSOSTEP',{212,  MAX_0b,MAX_16b},...
                'POWER_DOWN_DELAY'            ,{214,  MAX_1b,MAX_16b},...
                'MAX_EXTERNAL_ENCODER_DEVIAT' ,{218,  MAX_0b,MAX_16b},...
                'STEP_DIR_MODE'               ,{254,  MAX_1b,      5});
end
