function [axis_params] = axis_parameters_table_w_e()
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Function: axis_parameters_table_w_e()
% Goal    : Output a structure that contains all the axis parameters that
%           can be written and written to the EEPROM of the TMCM-1160.
%
% Structure fields:
% +-------------------------------------------------------+
% |Parameter name,{Parameter number, Min value, Max value}|
% +-------------------------------------------------------+
%
% IN      : -
% IN/OUT  : -
% OUT     : - axis_params: list of all write/EEPROM axis parameters for the
%                          TMCM-1160 with their MIN and MAX values
%
% Copyright 2018 The MathWorks, Inc.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

  % Constants of 2 power the number of bit
  MAX_0b  = 2^0 -1; MAX_1b  = 2^1 -1; MAX_2b  = 2^2 -1;
  MAX_4b  = 2^4 -1; MAX_5b  = 2^5 -1; MAX_6b  = 2^6 -1;
  MAX_8b  = 2^8 -1; MAX_11b = 2^11-1; MAX_16b = 2^16-1; MAX_31b = 2^31-1;
  
  % Mnemonic encoding in decimal for the available axis parameters
  axis_params = struct(...
                'TARGET_POSITION'             ,{  0,-MAX_31b,MAX_31b},...
                'ACTUAL_POSITION'             ,{  1,-MAX_31b,MAX_31b},...
                'TARGET_SPEED'                ,{  2,-MAX_11b,MAX_11b},...
                'ACTUAL_SPEED'                ,{  3,-MAX_11b,MAX_11b},...
                'MAX_POSITIONING_SPEED'       ,{  4,  MAX_0b,MAX_11b},...
                'MAX_ACCELERATION'            ,{  5,  MAX_0b,MAX_11b},...
                'ABSOLUTE_MAX_CURRENT'        ,{  6,  MAX_0b, MAX_8b},...
                'STANDBY_CURRENT'             ,{  7,  MAX_0b, MAX_8b},...
                'RIGHT_LIM_SWITCH_DISABLE'    ,{ 12,  MAX_0b, MAX_1b},...
                'LEFT_LIM_SWITCH_DISABLE'     ,{ 13,  MAX_0b, MAX_1b},...
                'MIN_SPEED'                   ,{130,  MAX_0b,MAX_11b},...
                'RAMP_MODE'                   ,{138,  MAX_0b,      2},...
                'MICROSTEP_RESOLUTION'        ,{140,  MAX_0b,      8},...
                'SOFT_STOP_FLAG'              ,{149,  MAX_0b, MAX_1b},...
                'RAMP_DIVISOR'                ,{153,  MAX_0b,     13},...
                'PULSE_DIVISOR'               ,{154,  MAX_0b,     13},...
                'STEP_INTERPOLATION_ENABLE'   ,{160,  MAX_0b, MAX_1b},...
                'DOUBLE_STEP_ENABLE'          ,{161,  MAX_0b, MAX_1b},...
                'CHOPPER_BLANK_TIME'          ,{162,  MAX_0b, MAX_2b},...
                'CHOPPER_MODE'                ,{163,  MAX_0b, MAX_1b},...
                'CHOPPER_HYSTERESIS_DEC'      ,{164,  MAX_0b, MAX_2b},...
                'CHOPPER_HYSTERESIS_END'      ,{165, -MAX_2b,     12},...
                'CHOPPER_HYSTERESIS_START'    ,{166,  MAX_0b,      8},...
                'CHOPPER_OFF_TIME'            ,{167,  MAX_0b, MAX_4b},...
                'SMARTENERGY_CURRENT_MIN'     ,{168,  MAX_0b, MAX_1b},...
                'SMARTENERGY_CURRENT_DOWN'    ,{169,  MAX_0b, MAX_2b},...
                'SMARTENERGY_HYSTERESIS'      ,{170,  MAX_0b, MAX_4b},...
                'SMARTENERGY_CURRENT_UP'      ,{171,  MAX_1b, MAX_2b},...
                'SMARTENERGY_HYSTERESIS_START',{172,  MAX_0b, MAX_4b},...
                'STALLGUARD2_FILTER_ENABLE'   ,{173,  MAX_0b, MAX_1b},...
                'STALLGUARD2_THRESHOLD'       ,{174, -MAX_6b, MAX_6b},...
                'SLOPE_CONTROL_HIGH_SIDE'     ,{175,  MAX_0b, MAX_2b},...
                'SLOPE_CONTROL_LOW_SIDE'      ,{176,  MAX_0b, MAX_2b},...
                'SHORT_PROTECTION_DISABLE'    ,{177,  MAX_0b, MAX_1b},...
                'SHORT_DETECTION_TIMER'       ,{178,  MAX_0b, MAX_2b},...
                'V_SENSE'                     ,{179,  MAX_0b, MAX_1b},...
                'SMARTENERGY_ACTUAL_CURRENT'  ,{180,  MAX_0b, MAX_5b},...
                'STOP_ON_STALL'               ,{181,  MAX_0b,MAX_11b},...
                'SMARTENERGY_THRESHOLD_SPEED' ,{182,  MAX_0b,MAX_11b},...
                'SMARTENERGY_SLOW_RUN_CURRENT',{183,  MAX_0b,MAX_11b},...
                'REFERENCE_SEARCH_MODE'       ,{193,  MAX_1b,      8},...
                'REFERENCING_SEARCH_SPEED'    ,{194,  MAX_0b,MAX_11b},...
                'REFERENCING_SWITCH_SPEED'    ,{195,  MAX_0b,MAX_11b},...
                'BOOST_CURRENT'               ,{200,  MAX_0b, MAX_8b},...
                'FREEWHEELING'                ,{204,  MAX_0b,MAX_16b},...
                'ENCODER_POSITION_SENSOSTEP'  ,{209,  MAX_0b,MAX_16b},...
                'ENCODER_PRESCALER_SENSOSTEP' ,{210,     200,  25600},...
                'MAX_ENCODER_DEVIAT_SENSOSTEP',{212,  MAX_0b,MAX_16b},...
                'POWER_DOWN_DELAY'            ,{214,  MAX_1b,MAX_16b},...
                'EXTERNAL_ENCODER_POSITION'   ,{216,  MAX_0b,MAX_16b},...
                'EXTERNAL_ENCODER_PRESCALER'  ,{217,     200,  25600},...
                'MAX_EXTERNAL_ENCODER_DEVIAT' ,{218,  MAX_0b,MAX_16b},...
                'STEP_DIR_MODE'               ,{254,  MAX_1b,      5});
end
